sudo: false
dist: trusty
language: elixir

elixir:
  - 1.4.5

otp_release:
  - 20.0
  - 19.3
  - 18.2

before_install:
  - kerl list installations
  - export MIX_ENV=ci

after_script:
  - mix credo --strict
  - mix hex.outdated
  - mix inch.report

after_success:
  - mix coveralls.travis
