sudo: false
dist: trusty
language: elixir

elixir:
  - 1.4.5

otp_release:
  - 20.0
  - 19.3
  - 18.2

cache:
  directories:
    - $HOME/.hex

before_install:
  - kerl list installations
  - export MIX_ENV=ci

after_script:
  - mix credo --strict
  - mix xref warnings
  - mix xref unreachable
  - mix inch.report
  - mix hex.outdated

after_success:
  - mix coveralls.travis
